spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver

    username: your_user
    password: your_password
    url: jdbc:mysql://localhost:3322/your_database

  jpa:
    show-sql: true
    defer-datasource-initialization: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
        generate_statistics: true
        order_inserts: true
        format_sql: true
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  token:
    key: h4PJIk1VKIn9PTBrw5dn8e7XCCA2CwPBZvw8MI0ZKJbi8i9ezQMtBKC25yCzZYyAy3gfr75GcIWpDkKWPbcvoM6mz3U5HA95B0h7HTGffPPKB7SQGmywL4hgB9seDteKmrKi140uxe413u48Nyho5BEsP12gMKTY6XxeKy7marvK0dgCeSJsZJBFvI1L84WdhZL0


