spring:
  application:
    name: boardExample

  datasource:
    username: test_user
    password: test_password
    url: jdbc:mysql://localhost:3307/test_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect