version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password   # 루트 계정 비밀번호
      MYSQL_DATABASE: your_database              # 기본 생성할 데이터베이스 이름
      MYSQL_USER: your_user                      # 추가 생성할 사용자 이름
      MYSQL_PASSWORD: your_password              # 추가 사용자의 비밀번호
    ports:
      - "3322:3306"                             # 호스트와 컨테이너의 포트 매핑

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always